export const productData = {
    title: 'All Products',
    categories: ['all', 'apple', 'samsung', 'huawei', 'xiaomi'],
    cards: [
        {
            title: 'Iphone 7',
            details: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti deserunt doloremque ipsa accusantium aspernatur ducimus labore accusamus repellat repellendus, sint animi quaerat reprehenderit iure dolorum temporibus sed voluptatum impedit ullam ipsam in totam pariatur omnis? Provident, deserunt inventore fuga totam, aut quam culpa officiis voluptatem distinctio quibusdam aliquam nemo unde eveniet quia corrupti commodi exercitationem sapiente velit dolorem doloremque et voluptates itaque. Non qui placeat debitis nemo assumenda accusantium nesciunt voluptates nam saepe! Recusandae nobis blanditiis, architecto nostrum maiores minima voluptates aliquam tempora delectus iste quisquam perferendis neque ipsa rerum? Voluptates dolorum placeat accusamus debitis quasi eligendi necessitatibus, commodi aliquid ratione. Excepturi asperiores maxime, laudantium quo voluptates officiis dicta libero, quod suscipit quas magnam obcaecati assumenda facere ratione mollitia molestias quae omnis similique ad voluptate id voluptas odit vero iste? Sed repudiandae quibusdam explicabo, sapiente consectetur molestiae delectus asperiores laboriosam ipsam debitis veniam adipisci aspernatur at voluptates enim dolore fuga! Labore odio quia assumenda est ipsum! Distinctio quas porro, aperiam nisi quibusdam id perspiciatis officia assumenda, obcaecati mollitia dolorum. Laboriosam modi aperiam cum nam, quas debitis sequi totam ullam quaerat nesciunt, pariatur aspernatur excepturi, rerum voluptatum optio esse reiciendis deserunt. Quis, modi porro perspiciatis velit beatae corrupti at sunt, iste neque earum reiciendis, quo vel? Repellat eaque ex voluptatem cumque temporibus quam expedita, sint aperiam, quaerat praesentium corrupti! Ipsa perspiciatis error cum non aut. Reprehenderit magnam alias voluptatem quisquam! Ex facere, doloremque in qui, accusantium magni nihil similique deleniti, excepturi enim deserunt aspernatur accusamus aut odio vitae neque ipsa provident!',
            image:'/images/apple/iphone_7.png',
            price:750,
            category: 'apple'
        },
        {
            title: 'Iphone Se',
            details: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti deserunt doloremque ipsa accusantium aspernatur ducimus labore accusamus repellat repellendus, sint animi quaerat reprehenderit iure dolorum temporibus sed voluptatum impedit ullam ipsam in totam pariatur omnis? Provident, deserunt inventore fuga totam, aut quam culpa officiis voluptatem distinctio quibusdam aliquam nemo unde eveniet quia corrupti commodi exercitationem sapiente velit dolorem doloremque et voluptates itaque. Non qui placeat debitis nemo assumenda accusantium nesciunt voluptates nam saepe! Recusandae nobis blanditiis, architecto nostrum maiores minima voluptates aliquam tempora delectus iste quisquam perferendis neque ipsa rerum? Voluptates dolorum placeat accusamus debitis quasi eligendi necessitatibus, commodi aliquid ratione. Excepturi asperiores maxime, laudantium quo voluptates officiis dicta libero, quod suscipit quas magnam obcaecati assumenda facere ratione mollitia molestias quae omnis similique ad voluptate id voluptas odit vero iste? Sed repudiandae quibusdam explicabo, sapiente consectetur molestiae delectus asperiores laboriosam ipsam debitis veniam adipisci aspernatur at voluptates enim dolore fuga! Labore odio quia assumenda est ipsum! Distinctio quas porro, aperiam nisi quibusdam id perspiciatis officia assumenda, obcaecati mollitia dolorum. Laboriosam modi aperiam cum nam, quas debitis sequi totam ullam quaerat nesciunt, pariatur aspernatur excepturi, rerum voluptatum optio esse reiciendis deserunt. Quis, modi porro perspiciatis velit beatae corrupti at sunt, iste neque earum reiciendis, quo vel? Repellat eaque ex voluptatem cumque temporibus quam expedita, sint aperiam, quaerat praesentium corrupti! Ipsa perspiciatis error cum non aut. Reprehenderit magnam alias voluptatem quisquam! Ex facere, doloremque in qui, accusantium magni nihil similique deleniti, excepturi enim deserunt aspernatur accusamus aut odio vitae neque ipsa provident!' ,
            image:'/images/apple/iphone_se.png',
            price:989,
            category: 'apple'
        },
        {
            title: 'Iphone Xr',
            details: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti deserunt doloremque ipsa accusantium aspernatur ducimus labore accusamus repellat repellendus, sint animi quaerat reprehenderit iure dolorum temporibus sed voluptatum impedit ullam ipsam in totam pariatur omnis? Provident, deserunt inventore fuga totam, aut quam culpa officiis voluptatem distinctio quibusdam aliquam nemo unde eveniet quia corrupti commodi exercitationem sapiente velit dolorem doloremque et voluptates itaque. Non qui placeat debitis nemo assumenda accusantium nesciunt voluptates nam saepe! Recusandae nobis blanditiis, architecto nostrum maiores minima voluptates aliquam tempora delectus iste quisquam perferendis neque ipsa rerum? Voluptates dolorum placeat accusamus debitis quasi eligendi necessitatibus, commodi aliquid ratione. Excepturi asperiores maxime, laudantium quo voluptates officiis dicta libero, quod suscipit quas magnam obcaecati assumenda facere ratione mollitia molestias quae omnis similique ad voluptate id voluptas odit vero iste? Sed repudiandae quibusdam explicabo, sapiente consectetur molestiae delectus asperiores laboriosam ipsam debitis veniam adipisci aspernatur at voluptates enim dolore fuga! Labore odio quia assumenda est ipsum! Distinctio quas porro, aperiam nisi quibusdam id perspiciatis officia assumenda, obcaecati mollitia dolorum. Laboriosam modi aperiam cum nam, quas debitis sequi totam ullam quaerat nesciunt, pariatur aspernatur excepturi, rerum voluptatum optio esse reiciendis deserunt. Quis, modi porro perspiciatis velit beatae corrupti at sunt, iste neque earum reiciendis, quo vel? Repellat eaque ex voluptatem cumque temporibus quam expedita, sint aperiam, quaerat praesentium corrupti! Ipsa perspiciatis error cum non aut. Reprehenderit magnam alias voluptatem quisquam! Ex facere, doloremque in qui, accusantium magni nihil similique deleniti, excepturi enim deserunt aspernatur accusamus aut odio vitae neque ipsa provident!',
            image:'/images/apple/iphone_xr.png',
            price:1000,
            category: 'apple'
        },
        {
            title: 'Iphone 11',
            details: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti deserunt doloremque ipsa accusantium aspernatur ducimus labore accusamus repellat repellendus, sint animi quaerat reprehenderit iure dolorum temporibus sed voluptatum impedit ullam ipsam in totam pariatur omnis? Provident, deserunt inventore fuga totam, aut quam culpa officiis voluptatem distinctio quibusdam aliquam nemo unde eveniet quia corrupti commodi exercitationem sapiente velit dolorem doloremque et voluptates itaque. Non qui placeat debitis nemo assumenda accusantium nesciunt voluptates nam saepe! Recusandae nobis blanditiis, architecto nostrum maiores minima voluptates aliquam tempora delectus iste quisquam perferendis neque ipsa rerum? Voluptates dolorum placeat accusamus debitis quasi eligendi necessitatibus, commodi aliquid ratione. Excepturi asperiores maxime, laudantium quo voluptates officiis dicta libero, quod suscipit quas magnam obcaecati assumenda facere ratione mollitia molestias quae omnis similique ad voluptate id voluptas odit vero iste? Sed repudiandae quibusdam explicabo, sapiente consectetur molestiae delectus asperiores laboriosam ipsam debitis veniam adipisci aspernatur at voluptates enim dolore fuga! Labore odio quia assumenda est ipsum! Distinctio quas porro, aperiam nisi quibusdam id perspiciatis officia assumenda, obcaecati mollitia dolorum. Laboriosam modi aperiam cum nam, quas debitis sequi totam ullam quaerat nesciunt, pariatur aspernatur excepturi, rerum voluptatum optio esse reiciendis deserunt. Quis, modi porro perspiciatis velit beatae corrupti at sunt, iste neque earum reiciendis, quo vel? Repellat eaque ex voluptatem cumque temporibus quam expedita, sint aperiam, quaerat praesentium corrupti! Ipsa perspiciatis error cum non aut. Reprehenderit magnam alias voluptatem quisquam! Ex facere, doloremque in qui, accusantium magni nihil similique deleniti, excepturi enim deserunt aspernatur accusamus aut odio vitae neque ipsa provident!',
            image:'/images/apple/iphone11.png',
            price:1049,
            category: 'apple'
        },
        {
            title: 'Iphone 11 Pro',
            details: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti deserunt doloremque ipsa accusantium aspernatur ducimus labore accusamus repellat repellendus, sint animi quaerat reprehenderit iure dolorum temporibus sed voluptatum impedit ullam ipsam in totam pariatur omnis? Provident, deserunt inventore fuga totam, aut quam culpa officiis voluptatem distinctio quibusdam aliquam nemo unde eveniet quia corrupti commodi exercitationem sapiente velit dolorem doloremque et voluptates itaque. Non qui placeat debitis nemo assumenda accusantium nesciunt voluptates nam saepe! Recusandae nobis blanditiis, architecto nostrum maiores minima voluptates aliquam tempora delectus iste quisquam perferendis neque ipsa rerum? Voluptates dolorum placeat accusamus debitis quasi eligendi necessitatibus, commodi aliquid ratione. Excepturi asperiores maxime, laudantium quo voluptates officiis dicta libero, quod suscipit quas magnam obcaecati assumenda facere ratione mollitia molestias quae omnis similique ad voluptate id voluptas odit vero iste? Sed repudiandae quibusdam explicabo, sapiente consectetur molestiae delectus asperiores laboriosam ipsam debitis veniam adipisci aspernatur at voluptates enim dolore fuga! Labore odio quia assumenda est ipsum! Distinctio quas porro, aperiam nisi quibusdam id perspiciatis officia assumenda, obcaecati mollitia dolorum. Laboriosam modi aperiam cum nam, quas debitis sequi totam ullam quaerat nesciunt, pariatur aspernatur excepturi, rerum voluptatum optio esse reiciendis deserunt. Quis, modi porro perspiciatis velit beatae corrupti at sunt, iste neque earum reiciendis, quo vel? Repellat eaque ex voluptatem cumque temporibus quam expedita, sint aperiam, quaerat praesentium corrupti! Ipsa perspiciatis error cum non aut. Reprehenderit magnam alias voluptatem quisquam! Ex facere, doloremque in qui, accusantium magni nihil similique deleniti, excepturi enim deserunt aspernatur accusamus aut odio vitae neque ipsa provident!' ,
            image:'/images/apple/iphone11_pro.png',
            price:1125,
            category: 'apple'
        },
        {
            title: 'Iphone Pro Max',
            details: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti deserunt doloremque ipsa accusantium aspernatur ducimus labore accusamus repellat repellendus, sint animi quaerat reprehenderit iure dolorum temporibus sed voluptatum impedit ullam ipsam in totam pariatur omnis? Provident, deserunt inventore fuga totam, aut quam culpa officiis voluptatem distinctio quibusdam aliquam nemo unde eveniet quia corrupti commodi exercitationem sapiente velit dolorem doloremque et voluptates itaque. Non qui placeat debitis nemo assumenda accusantium nesciunt voluptates nam saepe! Recusandae nobis blanditiis, architecto nostrum maiores minima voluptates aliquam tempora delectus iste quisquam perferendis neque ipsa rerum? Voluptates dolorum placeat accusamus debitis quasi eligendi necessitatibus, commodi aliquid ratione. Excepturi asperiores maxime, laudantium quo voluptates officiis dicta libero, quod suscipit quas magnam obcaecati assumenda facere ratione mollitia molestias quae omnis similique ad voluptate id voluptas odit vero iste? Sed repudiandae quibusdam explicabo, sapiente consectetur molestiae delectus asperiores laboriosam ipsam debitis veniam adipisci aspernatur at voluptates enim dolore fuga! Labore odio quia assumenda est ipsum! Distinctio quas porro, aperiam nisi quibusdam id perspiciatis officia assumenda, obcaecati mollitia dolorum. Laboriosam modi aperiam cum nam, quas debitis sequi totam ullam quaerat nesciunt, pariatur aspernatur excepturi, rerum voluptatum optio esse reiciendis deserunt. Quis, modi porro perspiciatis velit beatae corrupti at sunt, iste neque earum reiciendis, quo vel? Repellat eaque ex voluptatem cumque temporibus quam expedita, sint aperiam, quaerat praesentium corrupti! Ipsa perspiciatis error cum non aut. Reprehenderit magnam alias voluptatem quisquam! Ex facere, doloremque in qui, accusantium magni nihil similique deleniti, excepturi enim deserunt aspernatur accusamus aut odio vitae neque ipsa provident!',
            image:'/images/apple/iphone_promax.png',
            price:1250,
            category: 'apple'
        },
        {
            title: 'Nova 7 ',
            details: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti deserunt doloremque ipsa accusantium aspernatur ducimus labore accusamus repellat repellendus, sint animi quaerat reprehenderit iure dolorum temporibus sed voluptatum impedit ullam ipsam in totam pariatur omnis? Provident, deserunt inventore fuga totam, aut quam culpa officiis voluptatem distinctio quibusdam aliquam nemo unde eveniet quia corrupti commodi exercitationem sapiente velit dolorem doloremque et voluptates itaque. Non qui placeat debitis nemo assumenda accusantium nesciunt voluptates nam saepe! Recusandae nobis blanditiis, architecto nostrum maiores minima voluptates aliquam tempora delectus iste quisquam perferendis neque ipsa rerum? Voluptates dolorum placeat accusamus debitis quasi eligendi necessitatibus, commodi aliquid ratione. Excepturi asperiores maxime, laudantium quo voluptates officiis dicta libero, quod suscipit quas magnam obcaecati assumenda facere ratione mollitia molestias quae omnis similique ad voluptate id voluptas odit vero iste? Sed repudiandae quibusdam explicabo, sapiente consectetur molestiae delectus asperiores laboriosam ipsam debitis veniam adipisci aspernatur at voluptates enim dolore fuga! Labore odio quia assumenda est ipsum! Distinctio quas porro, aperiam nisi quibusdam id perspiciatis officia assumenda, obcaecati mollitia dolorum. Laboriosam modi aperiam cum nam, quas debitis sequi totam ullam quaerat nesciunt, pariatur aspernatur excepturi, rerum voluptatum optio esse reiciendis deserunt. Quis, modi porro perspiciatis velit beatae corrupti at sunt, iste neque earum reiciendis, quo vel? Repellat eaque ex voluptatem cumque temporibus quam expedita, sint aperiam, quaerat praesentium corrupti! Ipsa perspiciatis error cum non aut. Reprehenderit magnam alias voluptatem quisquam! Ex facere, doloremque in qui, accusantium magni nihil similique deleniti, excepturi enim deserunt aspernatur accusamus aut odio vitae neque ipsa provident!',
            image:'/images/huawei/nova7.jpg',
            price:649,
            category: 'huawei'
        },
        {
            title: ' P 30 ',
            details: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti deserunt doloremque ipsa accusantium aspernatur ducimus labore accusamus repellat repellendus, sint animi quaerat reprehenderit iure dolorum temporibus sed voluptatum impedit ullam ipsam in totam pariatur omnis? Provident, deserunt inventore fuga totam, aut quam culpa officiis voluptatem distinctio quibusdam aliquam nemo unde eveniet quia corrupti commodi exercitationem sapiente velit dolorem doloremque et voluptates itaque. Non qui placeat debitis nemo assumenda accusantium nesciunt voluptates nam saepe! Recusandae nobis blanditiis, architecto nostrum maiores minima voluptates aliquam tempora delectus iste quisquam perferendis neque ipsa rerum? Voluptates dolorum placeat accusamus debitis quasi eligendi necessitatibus, commodi aliquid ratione. Excepturi asperiores maxime, laudantium quo voluptates officiis dicta libero, quod suscipit quas magnam obcaecati assumenda facere ratione mollitia molestias quae omnis similique ad voluptate id voluptas odit vero iste? Sed repudiandae quibusdam explicabo, sapiente consectetur molestiae delectus asperiores laboriosam ipsam debitis veniam adipisci aspernatur at voluptates enim dolore fuga! Labore odio quia assumenda est ipsum! Distinctio quas porro, aperiam nisi quibusdam id perspiciatis officia assumenda, obcaecati mollitia dolorum. Laboriosam modi aperiam cum nam, quas debitis sequi totam ullam quaerat nesciunt, pariatur aspernatur excepturi, rerum voluptatum optio esse reiciendis deserunt. Quis, modi porro perspiciatis velit beatae corrupti at sunt, iste neque earum reiciendis, quo vel? Repellat eaque ex voluptatem cumque temporibus quam expedita, sint aperiam, quaerat praesentium corrupti! Ipsa perspiciatis error cum non aut. Reprehenderit magnam alias voluptatem quisquam! Ex facere, doloremque in qui, accusantium magni nihil similique deleniti, excepturi enim deserunt aspernatur accusamus aut odio vitae neque ipsa provident!',
            image:'/images/huawei/p.jpg',
            price:1080,
            category: 'huawei'
        },
        {
            title: 'P 6',
            details: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti deserunt doloremque ipsa accusantium aspernatur ducimus labore accusamus repellat repellendus, sint animi quaerat reprehenderit iure dolorum temporibus sed voluptatum impedit ullam ipsam in totam pariatur omnis? Provident, deserunt inventore fuga totam, aut quam culpa officiis voluptatem distinctio quibusdam aliquam nemo unde eveniet quia corrupti commodi exercitationem sapiente velit dolorem doloremque et voluptates itaque. Non qui placeat debitis nemo assumenda accusantium nesciunt voluptates nam saepe! Recusandae nobis blanditiis, architecto nostrum maiores minima voluptates aliquam tempora delectus iste quisquam perferendis neque ipsa rerum? Voluptates dolorum placeat accusamus debitis quasi eligendi necessitatibus, commodi aliquid ratione. Excepturi asperiores maxime, laudantium quo voluptates officiis dicta libero, quod suscipit quas magnam obcaecati assumenda facere ratione mollitia molestias quae omnis similique ad voluptate id voluptas odit vero iste? Sed repudiandae quibusdam explicabo, sapiente consectetur molestiae delectus asperiores laboriosam ipsam debitis veniam adipisci aspernatur at voluptates enim dolore fuga! Labore odio quia assumenda est ipsum! Distinctio quas porro, aperiam nisi quibusdam id perspiciatis officia assumenda, obcaecati mollitia dolorum. Laboriosam modi aperiam cum nam, quas debitis sequi totam ullam quaerat nesciunt, pariatur aspernatur excepturi, rerum voluptatum optio esse reiciendis deserunt. Quis, modi porro perspiciatis velit beatae corrupti at sunt, iste neque earum reiciendis, quo vel? Repellat eaque ex voluptatem cumque temporibus quam expedita, sint aperiam, quaerat praesentium corrupti! Ipsa perspiciatis error cum non aut. Reprehenderit magnam alias voluptatem quisquam! Ex facere, doloremque in qui, accusantium magni nihil similique deleniti, excepturi enim deserunt aspernatur accusamus aut odio vitae neque ipsa provident!',
            image:'/images/huawei/p6.png',
            price:1090,
            category: 'huawei'
        },
        {
            title: 'P 40',
            details: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti deserunt doloremque ipsa accusantium aspernatur ducimus labore accusamus repellat repellendus, sint animi quaerat reprehenderit iure dolorum temporibus sed voluptatum impedit ullam ipsam in totam pariatur omnis? Provident, deserunt inventore fuga totam, aut quam culpa officiis voluptatem distinctio quibusdam aliquam nemo unde eveniet quia corrupti commodi exercitationem sapiente velit dolorem doloremque et voluptates itaque. Non qui placeat debitis nemo assumenda accusantium nesciunt voluptates nam saepe! Recusandae nobis blanditiis, architecto nostrum maiores minima voluptates aliquam tempora delectus iste quisquam perferendis neque ipsa rerum? Voluptates dolorum placeat accusamus debitis quasi eligendi necessitatibus, commodi aliquid ratione. Excepturi asperiores maxime, laudantium quo voluptates officiis dicta libero, quod suscipit quas magnam obcaecati assumenda facere ratione mollitia molestias quae omnis similique ad voluptate id voluptas odit vero iste? Sed repudiandae quibusdam explicabo, sapiente consectetur molestiae delectus asperiores laboriosam ipsam debitis veniam adipisci aspernatur at voluptates enim dolore fuga! Labore odio quia assumenda est ipsum! Distinctio quas porro, aperiam nisi quibusdam id perspiciatis officia assumenda, obcaecati mollitia dolorum. Laboriosam modi aperiam cum nam, quas debitis sequi totam ullam quaerat nesciunt, pariatur aspernatur excepturi, rerum voluptatum optio esse reiciendis deserunt. Quis, modi porro perspiciatis velit beatae corrupti at sunt, iste neque earum reiciendis, quo vel? Repellat eaque ex voluptatem cumque temporibus quam expedita, sint aperiam, quaerat praesentium corrupti! Ipsa perspiciatis error cum non aut. Reprehenderit magnam alias voluptatem quisquam! Ex facere, doloremque in qui, accusantium magni nihil similique deleniti, excepturi enim deserunt aspernatur accusamus aut odio vitae neque ipsa provident!',
            image:'/images/huawei/p40.jpg',
            price:1000,
            category: 'huawei'
        },
        {
            title: 'A 51',
            details: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti deserunt doloremque ipsa accusantium aspernatur ducimus labore accusamus repellat repellendus, sint animi quaerat reprehenderit iure dolorum temporibus sed voluptatum impedit ullam ipsam in totam pariatur omnis? Provident, deserunt inventore fuga totam, aut quam culpa officiis voluptatem distinctio quibusdam aliquam nemo unde eveniet quia corrupti commodi exercitationem sapiente velit dolorem doloremque et voluptates itaque. Non qui placeat debitis nemo assumenda accusantium nesciunt voluptates nam saepe! Recusandae nobis blanditiis, architecto nostrum maiores minima voluptates aliquam tempora delectus iste quisquam perferendis neque ipsa rerum? Voluptates dolorum placeat accusamus debitis quasi eligendi necessitatibus, commodi aliquid ratione. Excepturi asperiores maxime, laudantium quo voluptates officiis dicta libero, quod suscipit quas magnam obcaecati assumenda facere ratione mollitia molestias quae omnis similique ad voluptate id voluptas odit vero iste? Sed repudiandae quibusdam explicabo, sapiente consectetur molestiae delectus asperiores laboriosam ipsam debitis veniam adipisci aspernatur at voluptates enim dolore fuga! Labore odio quia assumenda est ipsum! Distinctio quas porro, aperiam nisi quibusdam id perspiciatis officia assumenda, obcaecati mollitia dolorum. Laboriosam modi aperiam cum nam, quas debitis sequi totam ullam quaerat nesciunt, pariatur aspernatur excepturi, rerum voluptatum optio esse reiciendis deserunt. Quis, modi porro perspiciatis velit beatae corrupti at sunt, iste neque earum reiciendis, quo vel? Repellat eaque ex voluptatem cumque temporibus quam expedita, sint aperiam, quaerat praesentium corrupti! Ipsa perspiciatis error cum non aut. Reprehenderit magnam alias voluptatem quisquam! Ex facere, doloremque in qui, accusantium magni nihil similique deleniti, excepturi enim deserunt aspernatur accusamus aut odio vitae neque ipsa provident!',
            image:'/images/samsung/a51.jpg',
            price:500,
            category: 'samsung'
        },
        {
            title: 'Flip',
            details: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti deserunt doloremque ipsa accusantium aspernatur ducimus labore accusamus repellat repellendus, sint animi quaerat reprehenderit iure dolorum temporibus sed voluptatum impedit ullam ipsam in totam pariatur omnis? Provident, deserunt inventore fuga totam, aut quam culpa officiis voluptatem distinctio quibusdam aliquam nemo unde eveniet quia corrupti commodi exercitationem sapiente velit dolorem doloremque et voluptates itaque. Non qui placeat debitis nemo assumenda accusantium nesciunt voluptates nam saepe! Recusandae nobis blanditiis, architecto nostrum maiores minima voluptates aliquam tempora delectus iste quisquam perferendis neque ipsa rerum? Voluptates dolorum placeat accusamus debitis quasi eligendi necessitatibus, commodi aliquid ratione. Excepturi asperiores maxime, laudantium quo voluptates officiis dicta libero, quod suscipit quas magnam obcaecati assumenda facere ratione mollitia molestias quae omnis similique ad voluptate id voluptas odit vero iste? Sed repudiandae quibusdam explicabo, sapiente consectetur molestiae delectus asperiores laboriosam ipsam debitis veniam adipisci aspernatur at voluptates enim dolore fuga! Labore odio quia assumenda est ipsum! Distinctio quas porro, aperiam nisi quibusdam id perspiciatis officia assumenda, obcaecati mollitia dolorum. Laboriosam modi aperiam cum nam, quas debitis sequi totam ullam quaerat nesciunt, pariatur aspernatur excepturi, rerum voluptatum optio esse reiciendis deserunt. Quis, modi porro perspiciatis velit beatae corrupti at sunt, iste neque earum reiciendis, quo vel? Repellat eaque ex voluptatem cumque temporibus quam expedita, sint aperiam, quaerat praesentium corrupti! Ipsa perspiciatis error cum non aut. Reprehenderit magnam alias voluptatem quisquam! Ex facere, doloremque in qui, accusantium magni nihil similique deleniti, excepturi enim deserunt aspernatur accusamus aut odio vitae neque ipsa provident!' ,
            image:'/images/samsung/flip.webp',
            price:1249,
            category: 'samsung'
        },
        {
            title: 'Note 20',
            details: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti deserunt doloremque ipsa accusantium aspernatur ducimus labore accusamus repellat repellendus, sint animi quaerat reprehenderit iure dolorum temporibus sed voluptatum impedit ullam ipsam in totam pariatur omnis? Provident, deserunt inventore fuga totam, aut quam culpa officiis voluptatem distinctio quibusdam aliquam nemo unde eveniet quia corrupti commodi exercitationem sapiente velit dolorem doloremque et voluptates itaque. Non qui placeat debitis nemo assumenda accusantium nesciunt voluptates nam saepe! Recusandae nobis blanditiis, architecto nostrum maiores minima voluptates aliquam tempora delectus iste quisquam perferendis neque ipsa rerum? Voluptates dolorum placeat accusamus debitis quasi eligendi necessitatibus, commodi aliquid ratione. Excepturi asperiores maxime, laudantium quo voluptates officiis dicta libero, quod suscipit quas magnam obcaecati assumenda facere ratione mollitia molestias quae omnis similique ad voluptate id voluptas odit vero iste? Sed repudiandae quibusdam explicabo, sapiente consectetur molestiae delectus asperiores laboriosam ipsam debitis veniam adipisci aspernatur at voluptates enim dolore fuga! Labore odio quia assumenda est ipsum! Distinctio quas porro, aperiam nisi quibusdam id perspiciatis officia assumenda, obcaecati mollitia dolorum. Laboriosam modi aperiam cum nam, quas debitis sequi totam ullam quaerat nesciunt, pariatur aspernatur excepturi, rerum voluptatum optio esse reiciendis deserunt. Quis, modi porro perspiciatis velit beatae corrupti at sunt, iste neque earum reiciendis, quo vel? Repellat eaque ex voluptatem cumque temporibus quam expedita, sint aperiam, quaerat praesentium corrupti! Ipsa perspiciatis error cum non aut. Reprehenderit magnam alias voluptatem quisquam! Ex facere, doloremque in qui, accusantium magni nihil similique deleniti, excepturi enim deserunt aspernatur accusamus aut odio vitae neque ipsa provident!',
            image:'/images/samsung/note.jpg',
            price:1750,
            category: 'samsung'
        },
        {
            title: 'Note 10',
            details: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti deserunt doloremque ipsa accusantium aspernatur ducimus labore accusamus repellat repellendus, sint animi quaerat reprehenderit iure dolorum temporibus sed voluptatum impedit ullam ipsam in totam pariatur omnis? Provident, deserunt inventore fuga totam, aut quam culpa officiis voluptatem distinctio quibusdam aliquam nemo unde eveniet quia corrupti commodi exercitationem sapiente velit dolorem doloremque et voluptates itaque. Non qui placeat debitis nemo assumenda accusantium nesciunt voluptates nam saepe! Recusandae nobis blanditiis, architecto nostrum maiores minima voluptates aliquam tempora delectus iste quisquam perferendis neque ipsa rerum? Voluptates dolorum placeat accusamus debitis quasi eligendi necessitatibus, commodi aliquid ratione. Excepturi asperiores maxime, laudantium quo voluptates officiis dicta libero, quod suscipit quas magnam obcaecati assumenda facere ratione mollitia molestias quae omnis similique ad voluptate id voluptas odit vero iste? Sed repudiandae quibusdam explicabo, sapiente consectetur molestiae delectus asperiores laboriosam ipsam debitis veniam adipisci aspernatur at voluptates enim dolore fuga! Labore odio quia assumenda est ipsum! Distinctio quas porro, aperiam nisi quibusdam id perspiciatis officia assumenda, obcaecati mollitia dolorum. Laboriosam modi aperiam cum nam, quas debitis sequi totam ullam quaerat nesciunt, pariatur aspernatur excepturi, rerum voluptatum optio esse reiciendis deserunt. Quis, modi porro perspiciatis velit beatae corrupti at sunt, iste neque earum reiciendis, quo vel? Repellat eaque ex voluptatem cumque temporibus quam expedita, sint aperiam, quaerat praesentium corrupti! Ipsa perspiciatis error cum non aut. Reprehenderit magnam alias voluptatem quisquam! Ex facere, doloremque in qui, accusantium magni nihil similique deleniti, excepturi enim deserunt aspernatur accusamus aut odio vitae neque ipsa provident!' ,
            image:'/images/samsung/note1.jpeg',
            price:1300,
            category: 'samsung'
        },
        {
            title: 'Mi 10',
            details: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti deserunt doloremque ipsa accusantium aspernatur ducimus labore accusamus repellat repellendus, sint animi quaerat reprehenderit iure dolorum temporibus sed voluptatum impedit ullam ipsam in totam pariatur omnis? Provident, deserunt inventore fuga totam, aut quam culpa officiis voluptatem distinctio quibusdam aliquam nemo unde eveniet quia corrupti commodi exercitationem sapiente velit dolorem doloremque et voluptates itaque. Non qui placeat debitis nemo assumenda accusantium nesciunt voluptates nam saepe! Recusandae nobis blanditiis, architecto nostrum maiores minima voluptates aliquam tempora delectus iste quisquam perferendis neque ipsa rerum? Voluptates dolorum placeat accusamus debitis quasi eligendi necessitatibus, commodi aliquid ratione. Excepturi asperiores maxime, laudantium quo voluptates officiis dicta libero, quod suscipit quas magnam obcaecati assumenda facere ratione mollitia molestias quae omnis similique ad voluptate id voluptas odit vero iste? Sed repudiandae quibusdam explicabo, sapiente consectetur molestiae delectus asperiores laboriosam ipsam debitis veniam adipisci aspernatur at voluptates enim dolore fuga! Labore odio quia assumenda est ipsum! Distinctio quas porro, aperiam nisi quibusdam id perspiciatis officia assumenda, obcaecati mollitia dolorum. Laboriosam modi aperiam cum nam, quas debitis sequi totam ullam quaerat nesciunt, pariatur aspernatur excepturi, rerum voluptatum optio esse reiciendis deserunt. Quis, modi porro perspiciatis velit beatae corrupti at sunt, iste neque earum reiciendis, quo vel? Repellat eaque ex voluptatem cumque temporibus quam expedita, sint aperiam, quaerat praesentium corrupti! Ipsa perspiciatis error cum non aut. Reprehenderit magnam alias voluptatem quisquam! Ex facere, doloremque in qui, accusantium magni nihil similique deleniti, excepturi enim deserunt aspernatur accusamus aut odio vitae neque ipsa provident!' ,
            image:'/images/xiaomi/mi10.png',
            price:1100,
            category: 'xiaomi'
        },
        {
            title: 'Note 8',
            details: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti deserunt doloremque ipsa accusantium aspernatur ducimus labore accusamus repellat repellendus, sint animi quaerat reprehenderit iure dolorum temporibus sed voluptatum impedit ullam ipsam in totam pariatur omnis? Provident, deserunt inventore fuga totam, aut quam culpa officiis voluptatem distinctio quibusdam aliquam nemo unde eveniet quia corrupti commodi exercitationem sapiente velit dolorem doloremque et voluptates itaque. Non qui placeat debitis nemo assumenda accusantium nesciunt voluptates nam saepe! Recusandae nobis blanditiis, architecto nostrum maiores minima voluptates aliquam tempora delectus iste quisquam perferendis neque ipsa rerum? Voluptates dolorum placeat accusamus debitis quasi eligendi necessitatibus, commodi aliquid ratione. Excepturi asperiores maxime, laudantium quo voluptates officiis dicta libero, quod suscipit quas magnam obcaecati assumenda facere ratione mollitia molestias quae omnis similique ad voluptate id voluptas odit vero iste? Sed repudiandae quibusdam explicabo, sapiente consectetur molestiae delectus asperiores laboriosam ipsam debitis veniam adipisci aspernatur at voluptates enim dolore fuga! Labore odio quia assumenda est ipsum! Distinctio quas porro, aperiam nisi quibusdam id perspiciatis officia assumenda, obcaecati mollitia dolorum. Laboriosam modi aperiam cum nam, quas debitis sequi totam ullam quaerat nesciunt, pariatur aspernatur excepturi, rerum voluptatum optio esse reiciendis deserunt. Quis, modi porro perspiciatis velit beatae corrupti at sunt, iste neque earum reiciendis, quo vel? Repellat eaque ex voluptatem cumque temporibus quam expedita, sint aperiam, quaerat praesentium corrupti! Ipsa perspiciatis error cum non aut. Reprehenderit magnam alias voluptatem quisquam! Ex facere, doloremque in qui, accusantium magni nihil similique deleniti, excepturi enim deserunt aspernatur accusamus aut odio vitae neque ipsa provident!' ,
            image:'/images/xiaomi/note8.webp',
            price:1300,
            category: 'xiaomi'
        },
        {
            title: 'Note 9',
            details: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti deserunt doloremque ipsa accusantium aspernatur ducimus labore accusamus repellat repellendus, sint animi quaerat reprehenderit iure dolorum temporibus sed voluptatum impedit ullam ipsam in totam pariatur omnis? Provident, deserunt inventore fuga totam, aut quam culpa officiis voluptatem distinctio quibusdam aliquam nemo unde eveniet quia corrupti commodi exercitationem sapiente velit dolorem doloremque et voluptates itaque. Non qui placeat debitis nemo assumenda accusantium nesciunt voluptates nam saepe! Recusandae nobis blanditiis, architecto nostrum maiores minima voluptates aliquam tempora delectus iste quisquam perferendis neque ipsa rerum? Voluptates dolorum placeat accusamus debitis quasi eligendi necessitatibus, commodi aliquid ratione. Excepturi asperiores maxime, laudantium quo voluptates officiis dicta libero, quod suscipit quas magnam obcaecati assumenda facere ratione mollitia molestias quae omnis similique ad voluptate id voluptas odit vero iste? Sed repudiandae quibusdam explicabo, sapiente consectetur molestiae delectus asperiores laboriosam ipsam debitis veniam adipisci aspernatur at voluptates enim dolore fuga! Labore odio quia assumenda est ipsum! Distinctio quas porro, aperiam nisi quibusdam id perspiciatis officia assumenda, obcaecati mollitia dolorum. Laboriosam modi aperiam cum nam, quas debitis sequi totam ullam quaerat nesciunt, pariatur aspernatur excepturi, rerum voluptatum optio esse reiciendis deserunt. Quis, modi porro perspiciatis velit beatae corrupti at sunt, iste neque earum reiciendis, quo vel? Repellat eaque ex voluptatem cumque temporibus quam expedita, sint aperiam, quaerat praesentium corrupti! Ipsa perspiciatis error cum non aut. Reprehenderit magnam alias voluptatem quisquam! Ex facere, doloremque in qui, accusantium magni nihil similique deleniti, excepturi enim deserunt aspernatur accusamus aut odio vitae neque ipsa provident!' ,
            image:'/images/xiaomi/note9.webp',
            price:1420,
            category: 'xiaomi'
        },
        {
            title: 'Note 10',
            details: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti deserunt doloremque ipsa accusantium aspernatur ducimus labore accusamus repellat repellendus, sint animi quaerat reprehenderit iure dolorum temporibus sed voluptatum impedit ullam ipsam in totam pariatur omnis? Provident, deserunt inventore fuga totam, aut quam culpa officiis voluptatem distinctio quibusdam aliquam nemo unde eveniet quia corrupti commodi exercitationem sapiente velit dolorem doloremque et voluptates itaque. Non qui placeat debitis nemo assumenda accusantium nesciunt voluptates nam saepe! Recusandae nobis blanditiis, architecto nostrum maiores minima voluptates aliquam tempora delectus iste quisquam perferendis neque ipsa rerum? Voluptates dolorum placeat accusamus debitis quasi eligendi necessitatibus, commodi aliquid ratione. Excepturi asperiores maxime, laudantium quo voluptates officiis dicta libero, quod suscipit quas magnam obcaecati assumenda facere ratione mollitia molestias quae omnis similique ad voluptate id voluptas odit vero iste? Sed repudiandae quibusdam explicabo, sapiente consectetur molestiae delectus asperiores laboriosam ipsam debitis veniam adipisci aspernatur at voluptates enim dolore fuga! Labore odio quia assumenda est ipsum! Distinctio quas porro, aperiam nisi quibusdam id perspiciatis officia assumenda, obcaecati mollitia dolorum. Laboriosam modi aperiam cum nam, quas debitis sequi totam ullam quaerat nesciunt, pariatur aspernatur excepturi, rerum voluptatum optio esse reiciendis deserunt. Quis, modi porro perspiciatis velit beatae corrupti at sunt, iste neque earum reiciendis, quo vel? Repellat eaque ex voluptatem cumque temporibus quam expedita, sint aperiam, quaerat praesentium corrupti! Ipsa perspiciatis error cum non aut. Reprehenderit magnam alias voluptatem quisquam! Ex facere, doloremque in qui, accusantium magni nihil similique deleniti, excepturi enim deserunt aspernatur accusamus aut odio vitae neque ipsa provident!' ,
            image:'/images/xiaomi/note10.jpg',
            price:1160,
            category: 'xiaomi'
        },
    ]
}


export const saleProductData = {
    title: 'Sales Products',
    categories: ['all', 'apple', 'samsung', 'huawei', 'xiaomi'],
    cards: [
        {
            title: 'Iphone 7',
            details: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti deserunt doloremque ipsa accusantium aspernatur ducimus labore accusamus repellat repellendus, sint animi quaerat reprehenderit iure dolorum temporibus sed voluptatum impedit ullam ipsam in totam pariatur omnis? Provident, deserunt inventore fuga totam, aut quam culpa officiis voluptatem distinctio quibusdam aliquam nemo unde eveniet quia corrupti commodi exercitationem sapiente velit dolorem doloremque et voluptates itaque. Non qui placeat debitis nemo assumenda accusantium nesciunt voluptates nam saepe! Recusandae nobis blanditiis, architecto nostrum maiores minima voluptates aliquam tempora delectus iste quisquam perferendis neque ipsa rerum? Voluptates dolorum placeat accusamus debitis quasi eligendi necessitatibus, commodi aliquid ratione. Excepturi asperiores maxime, laudantium quo voluptates officiis dicta libero, quod suscipit quas magnam obcaecati assumenda facere ratione mollitia molestias quae omnis similique ad voluptate id voluptas odit vero iste? Sed repudiandae quibusdam explicabo, sapiente consectetur molestiae delectus asperiores laboriosam ipsam debitis veniam adipisci aspernatur at voluptates enim dolore fuga! Labore odio quia assumenda est ipsum! Distinctio quas porro, aperiam nisi quibusdam id perspiciatis officia assumenda, obcaecati mollitia dolorum. Laboriosam modi aperiam cum nam, quas debitis sequi totam ullam quaerat nesciunt, pariatur aspernatur excepturi, rerum voluptatum optio esse reiciendis deserunt. Quis, modi porro perspiciatis velit beatae corrupti at sunt, iste neque earum reiciendis, quo vel? Repellat eaque ex voluptatem cumque temporibus quam expedita, sint aperiam, quaerat praesentium corrupti! Ipsa perspiciatis error cum non aut. Reprehenderit magnam alias voluptatem quisquam! Ex facere, doloremque in qui, accusantium magni nihil similique deleniti, excepturi enim deserunt aspernatur accusamus aut odio vitae neque ipsa provident!',
            image:'/images/apple/iphone_7.png',
            price:750,
            category: 'apple'
        },
        {
            title: 'Iphone Se',
            details: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti deserunt doloremque ipsa accusantium aspernatur ducimus labore accusamus repellat repellendus, sint animi quaerat reprehenderit iure dolorum temporibus sed voluptatum impedit ullam ipsam in totam pariatur omnis? Provident, deserunt inventore fuga totam, aut quam culpa officiis voluptatem distinctio quibusdam aliquam nemo unde eveniet quia corrupti commodi exercitationem sapiente velit dolorem doloremque et voluptates itaque. Non qui placeat debitis nemo assumenda accusantium nesciunt voluptates nam saepe! Recusandae nobis blanditiis, architecto nostrum maiores minima voluptates aliquam tempora delectus iste quisquam perferendis neque ipsa rerum? Voluptates dolorum placeat accusamus debitis quasi eligendi necessitatibus, commodi aliquid ratione. Excepturi asperiores maxime, laudantium quo voluptates officiis dicta libero, quod suscipit quas magnam obcaecati assumenda facere ratione mollitia molestias quae omnis similique ad voluptate id voluptas odit vero iste? Sed repudiandae quibusdam explicabo, sapiente consectetur molestiae delectus asperiores laboriosam ipsam debitis veniam adipisci aspernatur at voluptates enim dolore fuga! Labore odio quia assumenda est ipsum! Distinctio quas porro, aperiam nisi quibusdam id perspiciatis officia assumenda, obcaecati mollitia dolorum. Laboriosam modi aperiam cum nam, quas debitis sequi totam ullam quaerat nesciunt, pariatur aspernatur excepturi, rerum voluptatum optio esse reiciendis deserunt. Quis, modi porro perspiciatis velit beatae corrupti at sunt, iste neque earum reiciendis, quo vel? Repellat eaque ex voluptatem cumque temporibus quam expedita, sint aperiam, quaerat praesentium corrupti! Ipsa perspiciatis error cum non aut. Reprehenderit magnam alias voluptatem quisquam! Ex facere, doloremque in qui, accusantium magni nihil similique deleniti, excepturi enim deserunt aspernatur accusamus aut odio vitae neque ipsa provident!' ,
            image:'/images/apple/iphone_se.png',
            price:989,
            category: 'apple'
        },
        {
            title: 'Nova 7 ',
            details: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti deserunt doloremque ipsa accusantium aspernatur ducimus labore accusamus repellat repellendus, sint animi quaerat reprehenderit iure dolorum temporibus sed voluptatum impedit ullam ipsam in totam pariatur omnis? Provident, deserunt inventore fuga totam, aut quam culpa officiis voluptatem distinctio quibusdam aliquam nemo unde eveniet quia corrupti commodi exercitationem sapiente velit dolorem doloremque et voluptates itaque. Non qui placeat debitis nemo assumenda accusantium nesciunt voluptates nam saepe! Recusandae nobis blanditiis, architecto nostrum maiores minima voluptates aliquam tempora delectus iste quisquam perferendis neque ipsa rerum? Voluptates dolorum placeat accusamus debitis quasi eligendi necessitatibus, commodi aliquid ratione. Excepturi asperiores maxime, laudantium quo voluptates officiis dicta libero, quod suscipit quas magnam obcaecati assumenda facere ratione mollitia molestias quae omnis similique ad voluptate id voluptas odit vero iste? Sed repudiandae quibusdam explicabo, sapiente consectetur molestiae delectus asperiores laboriosam ipsam debitis veniam adipisci aspernatur at voluptates enim dolore fuga! Labore odio quia assumenda est ipsum! Distinctio quas porro, aperiam nisi quibusdam id perspiciatis officia assumenda, obcaecati mollitia dolorum. Laboriosam modi aperiam cum nam, quas debitis sequi totam ullam quaerat nesciunt, pariatur aspernatur excepturi, rerum voluptatum optio esse reiciendis deserunt. Quis, modi porro perspiciatis velit beatae corrupti at sunt, iste neque earum reiciendis, quo vel? Repellat eaque ex voluptatem cumque temporibus quam expedita, sint aperiam, quaerat praesentium corrupti! Ipsa perspiciatis error cum non aut. Reprehenderit magnam alias voluptatem quisquam! Ex facere, doloremque in qui, accusantium magni nihil similique deleniti, excepturi enim deserunt aspernatur accusamus aut odio vitae neque ipsa provident!',
            image:'/images/huawei/nova7.jpg',
            price:649,
            category: 'huawei'
        },
        {
            title: 'Mi 10',
            details: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti deserunt doloremque ipsa accusantium aspernatur ducimus labore accusamus repellat repellendus, sint animi quaerat reprehenderit iure dolorum temporibus sed voluptatum impedit ullam ipsam in totam pariatur omnis? Provident, deserunt inventore fuga totam, aut quam culpa officiis voluptatem distinctio quibusdam aliquam nemo unde eveniet quia corrupti commodi exercitationem sapiente velit dolorem doloremque et voluptates itaque. Non qui placeat debitis nemo assumenda accusantium nesciunt voluptates nam saepe! Recusandae nobis blanditiis, architecto nostrum maiores minima voluptates aliquam tempora delectus iste quisquam perferendis neque ipsa rerum? Voluptates dolorum placeat accusamus debitis quasi eligendi necessitatibus, commodi aliquid ratione. Excepturi asperiores maxime, laudantium quo voluptates officiis dicta libero, quod suscipit quas magnam obcaecati assumenda facere ratione mollitia molestias quae omnis similique ad voluptate id voluptas odit vero iste? Sed repudiandae quibusdam explicabo, sapiente consectetur molestiae delectus asperiores laboriosam ipsam debitis veniam adipisci aspernatur at voluptates enim dolore fuga! Labore odio quia assumenda est ipsum! Distinctio quas porro, aperiam nisi quibusdam id perspiciatis officia assumenda, obcaecati mollitia dolorum. Laboriosam modi aperiam cum nam, quas debitis sequi totam ullam quaerat nesciunt, pariatur aspernatur excepturi, rerum voluptatum optio esse reiciendis deserunt. Quis, modi porro perspiciatis velit beatae corrupti at sunt, iste neque earum reiciendis, quo vel? Repellat eaque ex voluptatem cumque temporibus quam expedita, sint aperiam, quaerat praesentium corrupti! Ipsa perspiciatis error cum non aut. Reprehenderit magnam alias voluptatem quisquam! Ex facere, doloremque in qui, accusantium magni nihil similique deleniti, excepturi enim deserunt aspernatur accusamus aut odio vitae neque ipsa provident!' ,
            image:'/images/xiaomi/mi10.png',
            price:1100,
            category: 'xiaomi'
        },
        {
            title: 'Flip',
            details: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti deserunt doloremque ipsa accusantium aspernatur ducimus labore accusamus repellat repellendus, sint animi quaerat reprehenderit iure dolorum temporibus sed voluptatum impedit ullam ipsam in totam pariatur omnis? Provident, deserunt inventore fuga totam, aut quam culpa officiis voluptatem distinctio quibusdam aliquam nemo unde eveniet quia corrupti commodi exercitationem sapiente velit dolorem doloremque et voluptates itaque. Non qui placeat debitis nemo assumenda accusantium nesciunt voluptates nam saepe! Recusandae nobis blanditiis, architecto nostrum maiores minima voluptates aliquam tempora delectus iste quisquam perferendis neque ipsa rerum? Voluptates dolorum placeat accusamus debitis quasi eligendi necessitatibus, commodi aliquid ratione. Excepturi asperiores maxime, laudantium quo voluptates officiis dicta libero, quod suscipit quas magnam obcaecati assumenda facere ratione mollitia molestias quae omnis similique ad voluptate id voluptas odit vero iste? Sed repudiandae quibusdam explicabo, sapiente consectetur molestiae delectus asperiores laboriosam ipsam debitis veniam adipisci aspernatur at voluptates enim dolore fuga! Labore odio quia assumenda est ipsum! Distinctio quas porro, aperiam nisi quibusdam id perspiciatis officia assumenda, obcaecati mollitia dolorum. Laboriosam modi aperiam cum nam, quas debitis sequi totam ullam quaerat nesciunt, pariatur aspernatur excepturi, rerum voluptatum optio esse reiciendis deserunt. Quis, modi porro perspiciatis velit beatae corrupti at sunt, iste neque earum reiciendis, quo vel? Repellat eaque ex voluptatem cumque temporibus quam expedita, sint aperiam, quaerat praesentium corrupti! Ipsa perspiciatis error cum non aut. Reprehenderit magnam alias voluptatem quisquam! Ex facere, doloremque in qui, accusantium magni nihil similique deleniti, excepturi enim deserunt aspernatur accusamus aut odio vitae neque ipsa provident!' ,
            image:'/images/samsung/flip.webp',
            price:1249,
            category: 'samsung'
        },
        {
            title: 'Note 20',
            details: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti deserunt doloremque ipsa accusantium aspernatur ducimus labore accusamus repellat repellendus, sint animi quaerat reprehenderit iure dolorum temporibus sed voluptatum impedit ullam ipsam in totam pariatur omnis? Provident, deserunt inventore fuga totam, aut quam culpa officiis voluptatem distinctio quibusdam aliquam nemo unde eveniet quia corrupti commodi exercitationem sapiente velit dolorem doloremque et voluptates itaque. Non qui placeat debitis nemo assumenda accusantium nesciunt voluptates nam saepe! Recusandae nobis blanditiis, architecto nostrum maiores minima voluptates aliquam tempora delectus iste quisquam perferendis neque ipsa rerum? Voluptates dolorum placeat accusamus debitis quasi eligendi necessitatibus, commodi aliquid ratione. Excepturi asperiores maxime, laudantium quo voluptates officiis dicta libero, quod suscipit quas magnam obcaecati assumenda facere ratione mollitia molestias quae omnis similique ad voluptate id voluptas odit vero iste? Sed repudiandae quibusdam explicabo, sapiente consectetur molestiae delectus asperiores laboriosam ipsam debitis veniam adipisci aspernatur at voluptates enim dolore fuga! Labore odio quia assumenda est ipsum! Distinctio quas porro, aperiam nisi quibusdam id perspiciatis officia assumenda, obcaecati mollitia dolorum. Laboriosam modi aperiam cum nam, quas debitis sequi totam ullam quaerat nesciunt, pariatur aspernatur excepturi, rerum voluptatum optio esse reiciendis deserunt. Quis, modi porro perspiciatis velit beatae corrupti at sunt, iste neque earum reiciendis, quo vel? Repellat eaque ex voluptatem cumque temporibus quam expedita, sint aperiam, quaerat praesentium corrupti! Ipsa perspiciatis error cum non aut. Reprehenderit magnam alias voluptatem quisquam! Ex facere, doloremque in qui, accusantium magni nihil similique deleniti, excepturi enim deserunt aspernatur accusamus aut odio vitae neque ipsa provident!',
            image:'/images/samsung/note.jpg',
            price:1750,
            category: 'samsung'
        },
    ]
}